services:
  - type: web
    name: neurorag
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python run_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: USE_TF
        value: "0"
      - key: TRANSFORMERS_NO_TF
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: HF_HOME
        value: /tmp/huggingface